version: "3.9"
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    networks:
      - psm_default


networks:
  psm_default:
    external: true
