version: '3.9'
services:
  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
