version: "3.9"
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4222:4222"
    restart: always
    networks:
      - psm_default

networks:
  psm_default:
    external: true
